workflows:
    android-workflow-id:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_pro
        environment:
          android_signing:
          - innuendo_private_keystore
          vars:
            PACKAGE_NAME: "io.codemagic.sample.reactnative"
        scripts:
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Build Android release
          script: | 
            cd android
            ./gradlew bundleRelease
        artifacts:
          - android/app/build/outputs/**/*.aab
    ios-workflow-id:
        name: iOS Workflow
        # ......