workflows:
    android-workflow-id:
        name: Android Workflow
        max_build_duration: 120
        environment:
          groups:
          - google_credentials
          android_signing:
          - innuendo_private_key
          vars:
            PACKAGE_NAME: "io.codemagic.sample.reactnative"
        scripts:
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Build Android release
          script: |
            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "com.innuendomobile")
            if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]
              then
                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
              else
                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
            fi
            cd android
            ./gradlew clean
            ./gradlew bundleRelease -x bundleReleaseJsAndAssets
        artifacts:
          - android/app/build/outputs/**/*.aab
        publishing:
          email:
            recipients:
              - dorian.service@outlook.fr
            notify:
              success: true
              failure: false
          google_play:
            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
            track: internal
    ios-workflow-id:
        name: iOS Workflow
        # ......